//
//  HTTPClients.swift
//  ExampleStressAppCore
//
//  Eight HTTP client witnesses used by the higher-level service witnesses in
//  `Services.swift`. Each is a struct of `@Sendable` closures generated by
//  `@DependencyClient`, with `.live`, `.preview` and `.unimplemented` static
//  variants. Together they exercise:
//
//  - Many distinct `DependencyKey` types in the registry
//  - Cross-dependency resolution at *call* time (services hop through these)
//  - Sendable-clean witness shapes typical of production codebases
//
//  Domain logic is intentionally toy. The point is to push lots of values
//  through the resolver, not to model HTTP correctly.
//

import Dependence
import DependenceMacros
import Foundation

// MARK: - Auth

@DependencyClient
public struct AuthHTTPClient: Sendable {
    public var signIn: @Sendable (_ username: String, _ password: String) async throws -> String
    public var signOut: @Sendable (_ token: String) async throws -> Void
    public var refresh: @Sendable (_ token: String) async throws -> String
    public var validate: @Sendable (_ token: String) async throws -> Bool
}

extension AuthHTTPClient {
    public static let live = AuthHTTPClient(
        signIn: { user, _ in "live-token-for-\(user)" },
        signOut: { _ in },
        refresh: { token in token + "-refreshed" },
        validate: { _ in true }
    )
    public static let preview = AuthHTTPClient(
        signIn: { _, _ in "preview-token" },
        signOut: { _ in },
        refresh: { _ in "preview-token" },
        validate: { _ in true }
    )
}

// MARK: - Feed

public struct FeedItem: Sendable, Equatable {
    public let id: Int
    public let title: String
    public init(id: Int, title: String) { self.id = id; self.title = title }
}

@DependencyClient
public struct FeedHTTPClient: Sendable {
    public var page: @Sendable (_ cursor: Int) async throws -> [FeedItem]
    public var like: @Sendable (_ id: Int) async throws -> Void
    public var unlike: @Sendable (_ id: Int) async throws -> Void
}

extension FeedHTTPClient {
    public static let live = FeedHTTPClient(
        page: { c in (0..<10).map { FeedItem(id: c * 10 + $0, title: "live-\(c)-\($0)") } },
        like: { _ in },
        unlike: { _ in }
    )
    public static let preview = FeedHTTPClient(
        page: { c in (0..<3).map { FeedItem(id: c * 10 + $0, title: "preview-\($0)") } },
        like: { _ in },
        unlike: { _ in }
    )
}

// MARK: - Profile

public struct UserProfile: Sendable, Equatable {
    public let id: String
    public let displayName: String
    public init(id: String, displayName: String) { self.id = id; self.displayName = displayName }
}

@DependencyClient
public struct ProfileHTTPClient: Sendable {
    public var fetch: @Sendable (_ id: String) async throws -> UserProfile
    public var update: @Sendable (_ profile: UserProfile) async throws -> Void
}

extension ProfileHTTPClient {
    public static let live = ProfileHTTPClient(
        fetch: { id in UserProfile(id: id, displayName: "Live User \(id)") },
        update: { _ in }
    )
    public static let preview = ProfileHTTPClient(
        fetch: { id in UserProfile(id: id, displayName: "Preview User") },
        update: { _ in }
    )
}

// MARK: - Media

@DependencyClient
public struct MediaHTTPClient: Sendable {
    public var thumbnail: @Sendable (_ id: String) async throws -> Data
    public var upload: @Sendable (_ payload: Data) async throws -> String
}

extension MediaHTTPClient {
    public static let live = MediaHTTPClient(
        thumbnail: { _ in Data(count: 256) },
        upload: { _ in UUID().uuidString }
    )
    public static let preview = MediaHTTPClient(
        thumbnail: { _ in Data() },
        upload: { _ in "preview-asset" }
    )
}

// MARK: - Search

@DependencyClient
public struct SearchHTTPClient: Sendable {
    public var query: @Sendable (_ term: String) async throws -> [String]
    public var suggestions: @Sendable (_ prefix: String) async throws -> [String]
}

extension SearchHTTPClient {
    public static let live = SearchHTTPClient(
        query: { term in [term + "-1", term + "-2", term + "-3"] },
        suggestions: { prefix in (0..<5).map { "\(prefix)\($0)" } }
    )
    public static let preview = SearchHTTPClient(
        query: { _ in ["preview-result"] },
        suggestions: { _ in ["preview-suggestion"] }
    )
}

// MARK: - Analytics

@DependencyClient
public struct AnalyticsHTTPClient: Sendable {
    public var track: @Sendable (_ event: String, _ properties: [String: String]) async throws -> Void
    public var flush: @Sendable () async throws -> Void
}

extension AnalyticsHTTPClient {
    public static let live = AnalyticsHTTPClient(
        track: { _, _ in },
        flush: {}
    )
    public static let preview = AnalyticsHTTPClient(
        track: { _, _ in },
        flush: {}
    )
}

// MARK: - Notification

@DependencyClient
public struct NotificationHTTPClient: Sendable {
    public var register: @Sendable (_ deviceToken: String) async throws -> Void
    public var deregister: @Sendable (_ deviceToken: String) async throws -> Void
}

extension NotificationHTTPClient {
    public static let live = NotificationHTTPClient(
        register: { _ in },
        deregister: { _ in }
    )
    public static let preview = NotificationHTTPClient(
        register: { _ in },
        deregister: { _ in }
    )
}

// MARK: - Sync

@DependencyClient
public struct SyncHTTPClient: Sendable {
    public var pull: @Sendable (_ since: Date) async throws -> [String]
    public var push: @Sendable (_ payload: [String]) async throws -> Date
}

extension SyncHTTPClient {
    public static let live = SyncHTTPClient(
        pull: { _ in (0..<8).map { "live-delta-\($0)" } },
        push: { _ in Date(timeIntervalSince1970: 0) }
    )
    public static let preview = SyncHTTPClient(
        pull: { _ in ["preview-delta"] },
        push: { _ in Date(timeIntervalSince1970: 0) }
    )
}
