//
//  TestWitnesses.swift
//  ExampleStressAppCore
//
//  Hand-written `testWitness` statics that alias each type's
//  macro-generated `unimplemented` value.
//
//  The indirection is load-bearing, not stylistic: `@DependencyEntry`'s
//  `test:` argument is stamped into a macro expansion, and expansion
//  type-checking cannot reference members generated by *other* macro
//  expansions — `test: AuthHTTPClient.unimplemented` fails with "has no
//  member 'unimplemented'" even though the member is perfectly reachable
//  from ordinary code. Routing through these ordinary declarations keeps
//  the registry's `test:` arguments compiling.
//

import Foundation

extension AuthHTTPClient {
    /// The unimplemented witness under a name reachable from macro
    /// expansions (see the file header).
    public static let testWitness = AuthHTTPClient.unimplemented
}

extension FeedHTTPClient {
    /// The unimplemented witness under a name reachable from macro
    /// expansions (see the file header).
    public static let testWitness = FeedHTTPClient.unimplemented
}

extension ProfileHTTPClient {
    /// The unimplemented witness under a name reachable from macro
    /// expansions (see the file header).
    public static let testWitness = ProfileHTTPClient.unimplemented
}

extension MediaHTTPClient {
    /// The unimplemented witness under a name reachable from macro
    /// expansions (see the file header).
    public static let testWitness = MediaHTTPClient.unimplemented
}

extension SearchHTTPClient {
    /// The unimplemented witness under a name reachable from macro
    /// expansions (see the file header).
    public static let testWitness = SearchHTTPClient.unimplemented
}

extension AnalyticsHTTPClient {
    /// The unimplemented witness under a name reachable from macro
    /// expansions (see the file header).
    public static let testWitness = AnalyticsHTTPClient.unimplemented
}

extension NotificationHTTPClient {
    /// The unimplemented witness under a name reachable from macro
    /// expansions (see the file header).
    public static let testWitness = NotificationHTTPClient.unimplemented
}

extension SyncHTTPClient {
    /// The unimplemented witness under a name reachable from macro
    /// expansions (see the file header).
    public static let testWitness = SyncHTTPClient.unimplemented
}

extension AuthService {
    /// The unimplemented witness under a name reachable from macro
    /// expansions (see the file header).
    public static let testWitness = AuthService.unimplemented
}

extension FeedService {
    /// The unimplemented witness under a name reachable from macro
    /// expansions (see the file header).
    public static let testWitness = FeedService.unimplemented
}

extension ProfileService {
    /// The unimplemented witness under a name reachable from macro
    /// expansions (see the file header).
    public static let testWitness = ProfileService.unimplemented
}

extension MediaService {
    /// The unimplemented witness under a name reachable from macro
    /// expansions (see the file header).
    public static let testWitness = MediaService.unimplemented
}

extension SearchService {
    /// The unimplemented witness under a name reachable from macro
    /// expansions (see the file header).
    public static let testWitness = SearchService.unimplemented
}

extension AnalyticsService {
    /// The unimplemented witness under a name reachable from macro
    /// expansions (see the file header).
    public static let testWitness = AnalyticsService.unimplemented
}

extension NotificationService {
    /// The unimplemented witness under a name reachable from macro
    /// expansions (see the file header).
    public static let testWitness = NotificationService.unimplemented
}

extension SyncService {
    /// The unimplemented witness under a name reachable from macro
    /// expansions (see the file header).
    public static let testWitness = SyncService.unimplemented
}

extension CacheService {
    /// The unimplemented witness under a name reachable from macro
    /// expansions (see the file header).
    public static let testWitness = CacheService.unimplemented
}

extension LoggerService {
    /// The unimplemented witness under a name reachable from macro
    /// expansions (see the file header).
    public static let testWitness = LoggerService.unimplemented
}

extension FeatureFlagService {
    /// The unimplemented witness under a name reachable from macro
    /// expansions (see the file header).
    public static let testWitness = FeatureFlagService.unimplemented
}

extension SessionService {
    /// The unimplemented witness under a name reachable from macro
    /// expansions (see the file header).
    public static let testWitness = SessionService.unimplemented
}
